### ISSUE TITLE
Spelling/Item Names

### ISSUE THREAD

**Issue by Tutterss** [Mustafa12315/Studio-2#10]
Some Item names need work, pain killerrr for example, you have to type painkiller in order to pick it up, the game also lists bandages with the s but to add the bandages you have to just type bandage. Bulletproof vest at the start is also an issue, it is listed as bulletproof vest but to add item you must just type vest.
Could be more.

**Comment by Tutterss** [comment]
at beach you have to type proceed to proceed, at school you have to say yes to proceed

**Comment by Mustafa12315** [comment]
I changed the proceed from beach to "yes"

**Comment by Tutterss** [comment]
Changed spelling of painkiller, bulletproof vest, bandages and convenience store.

**Comment by Mustafa12315** [comment]
Spelling issues solved.
